// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "common services": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/ZJU-DistributedAI/Common/design
// --out=$(GOPATH)/src/github.com/ZJU-DistributedAI/Common
// --version=v1.3.1

package client
