// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "common services": Application User Types
//
// Command:
// $ goagen
// --design=github.com/ZJU-DistributedAI/Common/design
// --out=$(GOPATH)/src/github.com/ZJU-DistributedAI/Common
// --version=v1.3.1

package client

// filePayload user type.
type filePayload struct {
	// file
	File *string `form:"file,omitempty" json:"file,omitempty" yaml:"file,omitempty" xml:"file,omitempty"`
}

// Publicize creates FilePayload from filePayload
func (ut *filePayload) Publicize() *FilePayload {
	var pub FilePayload
	if ut.File != nil {
		pub.File = ut.File
	}
	return &pub
}

// FilePayload user type.
type FilePayload struct {
	// file
	File *string `form:"file,omitempty" json:"file,omitempty" yaml:"file,omitempty" xml:"file,omitempty"`
}
